apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-poi-deploy
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights-poi-app
  template:
    metadata:
      labels:
        app: tripinsights-poi-app
        aadpodidbinding: identityenabled
    spec:
      containers:
      - name: poi
        image: registryftf5727.azurecr.io/poi:1.0
        volumeMounts:
        - name: test
          mountPath: /secrets
          readOnly: true
        env:
        - name: SQL_USER
          value: "sqladminfTf5727"
        - name: SQL_SERVER
          value: "sqlserverftf5727.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
      volumes:
      - name: test
        flexVolume:
          driver: "azure/kv"
          options:
            usepodidentity: "true"
            keyvaultname: "ohaks-keyvault"
            keyvaultobjectnames: "SQLPASSWORD"
            keyvaultobjectaliases: "SQL_PASSWORD"
            keyvaultobjecttypes: secret
            resourcegroup: "teamResources"
            subscriptionid: "676afd27-7ef9-48fe-b892-3e40a48d3385"
            tenantid: "320aa98e-f000-47f8-a7da-aad28653e19b"
