apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azureidentity-oh
spec:
  type: 0
  ResourceID: /subscriptions/676afd27-7ef9-48fe-b892-3e40a48d3385/resourcegroups/teamResources/providers/Microsoft.ManagedIdentity/userAssignedIdentities/oh-identity
  ClientID: e243f04c-87c9-4238-ba93-ba5791eefbdb
