apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ohaks-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hacker2lli@OTAPRD310ops.onmicrosoft.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hacker33kk@OTAPRD310ops.onmicrosoft.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hacker678t@OTAPRD310ops.onmicrosoft.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hacker4czf@OTAPRD310ops.onmicrosoft.com
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hacker1x8a@OTAPRD310ops.onmicrosoft.com
