apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-tripviewer-deploy
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripinsights-tripviewer-app
  template:
    metadata:
      labels:
        app: tripinsights-tripviewer-app
    spec:
      containers:
      - name: travelviewer
        image: registryftf5727.azurecr.io/tripviewer:1.0
        env:
        - name: USER_API_ENDPOINT
          value: "http://userprofile-service.api"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.api"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  selector:
    app: tripinsights-tripviewer-app
  ports:
  - port: 80